TASK: heatmap
PRECISION: float32
DATASET:
  type: HeatmapFaceForensic
  TRAIN: True
  ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c23/
  # FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  FAKETYPE: [FaceXRay]
  IMAGE_SUFFIX: jpg
  FROM_FILE: True
  NUM_WORKERS: 8
  PIN_MEMORY: True
  IMAGE_SIZE: [256, 256]
  HEATMAP_SIZE: [64, 64]
  SIGMA: 2
  HEATMAP_TYPE: gaussian
  DATA:
    TYPE: images
    TRAIN:
      ANNO_FILE: FaceXRay/train/train_FF_Xray.json
    VAL:
      ANNO_FILE: FaceXRay/val/val_FF_Xray.json
    TEST:
      ANNO_FILE: FaceXRay/test/test_FF_Xray.json
  TRANSFORM:
    geometry:
      type: GeometryTransform
      resize: [256, 256, 0] #h, w, p=probability. If no affine transform, set p=1
    color:
      type: ColorJitterTransform
      clahe: 0.5
      colorjitter: 0.5
      gaussianblur: 0.5
      jpegcompression: 0.5
      rgbshift: 0.5
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  DEBUG: False
MODEL:
  type: SimpleClassificationDF
  backbone:
    type: ResNet
    num_layers: 50
    drop_ratio: 0.5
    mode: ir_se
  head:
    type: SimpleClassificationHead
    drop_ratio: 0.5
    in_planes: 512
TRAIN:
  gpus: [0,1,2,3]
  batch_size: 32
  lr: 0.001
  epochs: 100
  begin_epoch: 0
  warm_up: 5
  every_val_epochs: 3
  loss:
    type: CombinedLoss
    use_target_weight: False
  optimizer: Adam
  distributed: False
  pretrained: pretrained/model_ir_se50.pth
  tensorboard: True
  resume: False
  lr_scheduler:
    # type: MultiStepLR
    milestones: [50, 80, 90]
    gamma: 0.1
PREPROCESSING:
  DATASET: FaceForensics
  SPLIT: train
  ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c23/
  FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  IMAGE_SUFFIX: jpg
  DATA_TYPE: images
  LABEL: real
  facial_lm_pretrained: pretrained/shape_predictor_68_face_landmarks.dat
