TASK: EFN_hm100_FPN_NoBasedCLS_Focal_C3_256Cstency10_32FXRayv1_SAM(Adam)
PRECISION: float64
METRICS_BASE: binary
SEED: 317
DATA_RELOAD: True
DATASET:
  type: HeatmapFaceForensic
  NAME: Celeb-DFv1 # This field to define datasets that can be used to train/in-dataset/cross-dataset evaluation
  TRAIN: False #Switch to True for training mode, False for testing mode
  # ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c0/
  # ROOT: /home/users/<user>/data/FaceForensics++/c0/
  # ROOT: /data/deepfake_cluster/datasets_df/Celeb-DFv1/
  ROOT: /home/users/<user>/data/Celeb-DFv1/
  # ROOT: /home/users/<user>/data/Celeb-DFv2/
  # ROOT: /home/users/<user>/data/DFDCP/
  # ROOT: /home/users/<user>/data/DFDC/
  # FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  COMPRESSION: c0
  IMAGE_SUFFIX: png
  FROM_FILE: False
  NUM_WORKERS: 7
  PIN_MEMORY: True
  IMAGE_SIZE: [384, 384]
  HEATMAP_SIZE: [96, 96] #[IMAGE_SIZE//4, IMAGE_SIZE//4]
  SIGMA: 2
  ADAPTIVE_SIGMA: True
  HEATMAP_TYPE: gaussian
  SPLIT_IMAGE: False
  DATA:
    TYPE: frames
    SAMPLES_PER_VIDEO: 
      ACTIVE: True
      TRAIN: 32
      VAL: 32
      TEST: 32
    TRAIN:
      FAKETYPE: [FaceXRay]
      # ANNO_FILE: train/frames/FaceXRay/train_FF_FaceXRay.json
      ANNO_FILE: processed_data/c0/dynamic_trainBI_FFv2.json
      LABEL_FOLDER: [real, fake]
    VAL:
      FAKETYPE: [FaceXRay]
      # ANNO_FILE: val/frames/FaceXRay/val_FF_FaceXRay.json
      ANNO_FILE: processed_data/c0/dynamic_valBI_FFv2.json
      LABEL_FOLDER: [real, fake]
    TEST:
      # FAKETYPE: [original, Deepfakes]
      # FAKETYPE: [original, Deepfakes, Face2Face, FaceSwap, NeuralTextures]
      FAKETYPE: [Celeb-real, Celeb-synthesis, YouTube-real]
      # FAKETYPE: [method_A, method_B, original_videos]
      # FAKETYPE: [fake, real]
      ANNO_FILE: FaceXRay/test/test_FF_Xray.json
      LABEL_FOLDER: [real, fake]
  TRANSFORM:
    geometry:
      type: GeometryTransform
      resize: [384, 384, 0] #h, w, p=probability. If no affine transform, set p=1
      normalize: 0
      horizontal_flip: 0.5
      cropping: [0.15, 0.5] #Format: [crop_limit, prob]
      scale: [0.15, 0.5] #Format: [scale_limit, prob]
      rand_erasing: [0.5, 3] #Format: [p, max_count]
    color:
      type: ColorJitterTransform
      clahe: 0.0
      colorjitter: 0.3
      gaussianblur: 0.3
      gaussnoise: 0.3
      jpegcompression: [0.5, 40, 100] # prob, lower and upper quality respectively
      rgbshift: 0.3
      randomcontrast: 0.0
      randomgamma: 0.5
      randombrightness: 1
      huesat: 1
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  DEBUG: False
  DYNAMIC_FXRAY: True
MODEL:
  type: PoseEfficientNet
  model_name: efficientnet-b4
  num_layers: B4
  include_top: False
  include_hm_decoder: True
  head_conv: 64
  use_c2: False
  use_c3: True
  use_c4: True
  use_c51: True
  fpn: True
  heads:
    hm: 1
    cls: 1
    cstency: 256
  INIT_WEIGHTS:
    pretrained: True
TRAIN:
  gpus: [0]
  batch_size: 32
  lr: 0.00025
  epochs: 100
  begin_epoch: 0
  warm_up: 6
  every_val_epochs: 1
  loss:
    type: CombinedFocalLoss
    use_target_weight: False
    cls_lmda: 1
    dst_hm_cls_lmda: 0
    offset_lmda: 0
    hm_lmda: 100
    cstency_lmda: 10
    mse_reduction: sum
    ce_reduction: mean
  optimizer: SAM
  distributed: False
  pretrained: ''
  tensorboard: True
  resume: False
  lr_scheduler:
    # type: MultiStepLR
    milestones: [5, 15, 20, 25]
    gamma: 0.5
  freeze_backbone: True
  debug:
    active: False
    save_hm_gt: True
    save_hm_pred: True
TEST:
  gpus: [0]
  subtask: 'eval'
  test_file: ''
  vis_hm: True
  threshold: 0.5
  flip_test: False
  pretrained: 'logs/20-02-2023/PoseEfficientNet_EFN_hm100_FPN_Based_CLS_Focal_NoC2_256Cstency10_32FXRayv2_SAM(Adam)_model_best.pth'
PREPROCESSING:
  DATASET: FaceForensics
  SPLIT: train
  ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c23/
  FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  IMAGE_SUFFIX: jpg
  DATA_TYPE: images
  LABEL: [real, fake]
  facial_lm_pretrained: pretrained/shape_predictor_68_face_landmarks.dat
  DEBUG: False
