TASK: heatmap_FPN_Separated_CLS_Focal_Deepfakes
PRECISION: float64
DATASET:
  type: HeatmapFaceForensic
  TRAIN: False #Switch to True for training mode, False for testing mode
  ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c23/
  # ROOT: /home/users/<user>/data/FaceForensics++/c23/
  # FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  IMAGE_SUFFIX: jpg
  FROM_FILE: False
  NUM_WORKERS: 14
  PIN_MEMORY: True
  IMAGE_SIZE: [256, 256]
  HEATMAP_SIZE: [64, 64] #[IMAGE_SIZE//4, IMAGE_SIZE//4]
  SIGMA: 2
  ADAPTIVE_SIGMA: True
  HEATMAP_TYPE: gaussian
  DATA:
    TYPE: images
    TRAIN:
      FAKETYPE: [Deepfakes_FaceXRay]
      ANNO_FILE: Deepfakes_FaceXRay/val/val_FF_Deepfakes_Xray.json
      # ANNO_FILE: FaceXRay/train/new_trainBI_FF.json
      # ANNO_FILE: processed_data/new_valBI_FF.json
      LABEL_FOLDER: [real, fake]
    VAL:
      FAKETYPE: [Deepfakes_FaceXRay]
      ANNO_FILE: Deepfakes_FaceXRay/val/val_FF_Deepfakes_Xray.json
      # ANNO_FILE: processed_data/new_valBI_FF.json
      LABEL_FOLDER: [real, fake]
    TEST:
      FAKETYPE: [Deepfakes]
      ANNO_FILE: FaceXRay/test/test_FF_Xray.json
      LABEL_FOLDER: [real, fake]
  TRANSFORM:
    geometry:
      type: GeometryTransform
      resize: [256, 256, 0] # h, w, p=probability. If no affine transform, set p=1
      normalize: 0
      horizontal_flip: 0.3
    color:
      type: ColorJitterTransform
      clahe: 0.0
      colorjitter: 0.3
      gaussianblur: 0.3
      jpegcompression: 0.5
      rgbshift: 0.3
      randomcontrast: 0.0
      randomgamma: 0.5
      randombrightness: 1
      huesat: 1
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  DEBUG: False
  DYNAMIC_FXRAY: False
MODEL:
  type: PoseResNet
  num_layers: 50
  # block: Bottleneck
  layers: [3, 4, 6, 3]
  heads:
    hm: 1
    cls: 1
  head_conv: 64
  dropout_prob: 0.5
  fpn: True
  cls_based_hm: False
  use_c2: False
TRAIN:
  gpus: [0,1,2,3]
  batch_size: 32
  lr: 0.001
  epochs: 30
  begin_epoch: 0
  warm_up: 6
  every_val_epochs: 1
  loss:
    type: CombinedFocalLoss
    use_target_weight: False
    cls_lmda: 1
    # dst_lmda: 0.05
    reduction: 'mean'
    # dist_cal: False
    cls_cal: True
  optimizer: Adam
  distributed: False
  # pretrained: 'logs/05-12-2022/PoseResNet_heatmap_FPN_Separated_CLS_Focal_NoFrZ_model_best.pth'
  tensorboard: True
  resume: False
  lr_scheduler:
    # type: MultiStepLR
    milestones: [6, 15, 20, 25]
    gamma: 0.5
  freeze_backbone: False
  debug:
    save_hm_gt: True
    save_hm_pred: True
TEST:
  gpus: [0,1,2,3]
  subtask: 'eval'
  test_file: ''
  vis_hm: True
  threshold: 0.5
  pretrained: 'logs/08-12-2022/PoseResNet_heatmap_FPN_Separated_CLS_Focal_Deepfakes_model_best.pth'
PREPROCESSING:
  DATASET: FaceForensics
  SPLIT: train
  ROOT: /data/deepfake_cluster/datasets_df/FaceForensics++/c23/
  FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  IMAGE_SUFFIX: jpg
  DATA_TYPE: images
  LABEL: [real, fake]
  facial_lm_pretrained: pretrained/shape_predictor_68_face_landmarks.dat
  DEBUG: False
